service: hywep-recruit-raw

plugins:
  - serverless-offline
  - serverless-docker-artifacts

custom:
  docker:
    image: hywep-recruit-crawler-image
    build:
      path: .
    push:
      repository: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${opt:region, 'ap-northeast-2'}.amazonaws.com/hywep-recruit-crawler-${opt:stage, 'dev'}
      tag: latest

  bucketNames:
    dev: hywep-recruit-raw-dev
    qa: hywep-recruit-raw-qa
    prod: hywep-recruit-raw-prod

  queueNames:
    dev: hywep-recruit-queue-dev
    qa: hywep-recruit-queue-qa
    prod: hywep-recruit-queue-prod

  ecrRepoNames:
    dev: hywep-recruit-crawler-dev
    qa: hywep-recruit-crawler-qa
    prod: hywep-recruit-crawler-prod

  schedules:
    dev: rate(6 hours)
    qa: rate(6 hours)
    prod: rate(3 hours)

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  ecr:
    images:
      hywep-recruit-crawler-image:
        path: .
  environment:
    HYWE_RECRUIT_BUCKET_NAME: ${self:custom.bucketNames.${opt:stage, 'dev'}}
    HYWE_LOGIN_USERNAME: ${env:HYWE_LOGIN_USERNAME}
    HYWE_LOGIN_PASSWORD: ${env:HYWE_LOGIN_PASSWORD}
    SQS_QUEUE_URL:
      Ref: HywepRecruitQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${self:custom.bucketNames.${opt:stage, 'dev'}}
            - arn:aws:s3:::${self:custom.bucketNames.${opt:stage, 'dev'}}/*
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt HywepRecruitQueue.Arn

functions:
  crawler:
    image:
      name: hywep-recruit-crawler-image
    timeout: 600
    memorySize: 1024
    events:
      - schedule: ${self:custom.schedules.${opt:stage, 'dev'}}

resources:
  Resources:
    HywepRawBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketNames.${opt:stage, 'dev'}}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    HywepRecruitCrawlerECR:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.ecrRepoNames.${opt:stage, 'dev'}}

    HywepRecruitQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueNames.${opt:stage, 'dev'}}

  Outputs:
    HywepRecruitQueueArn:
      Value: !GetAtt HywepRecruitQueue.Arn
      Export:
        Name: ${self:service}-${opt:stage, 'dev'}-HywepRecruitQueueArn
