service: hywep-recruit-crawler

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    BUCKET_NAME: ${env:HYWE_RECRUIT_BUCKET_NAME}
    HYWE_LOGIN_USERNAME: ${env:HYWE_LOGIN_USERNAME}
    HYWE_LOGIN_PASSWORD: ${env:HYWE_LOGIN_PASSWORD}
    SQS_QUEUE_URL:
      Ref: HywepRecruitQueue
  ecr:
    images:
      hywep-recruit-crawler-image:
        path: .
        platform: linux/amd64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::hywep-recruit-raw
            - arn:aws:s3:::hywep-recruit-raw/*
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt HywepRecruitQueue.Arn

functions:
  crawler:
    image:
      name: hywep-recruit-crawler-image
    timeout: 600
    memorySize: 1024
    events:
      - schedule: rate(3 hours)

resources:
  Resources:
    HywepRawBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hywep-recruit-raw
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    HywepRecruitCrawlerECR:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: hywep-recruit-crawler

    HywepRecruitQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: hywep-recruit-queue
