name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          npm install serverless@3 -g
          npm install

      - name: Deploy to Lambda
        run: |
          sls deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HYWE_LOGIN_USERNAME: ${{ secrets.HYWE_LOGIN_USERNAME }}
          HYWE_LOGIN_PASSWORD: ${{ secrets.HYWE_LOGIN_PASSWORD }}
          HYWE_RECRUIT_BUCKET_NAME: ${{ secrets.HYWE_RECRUIT_BUCKET_NAME }}
